version: "3"

services:

  frontend:
      container_name: ${PROJECT_NAME}_frontend
      build:
        context: ${BASE_DIR}/frontend
        dockerfile: .DockerfileFrontend
      expose:
        - ${FRONTEND_PORT}
      volumes:
        - ${BASE_DIR}/frontend:/frontend
      depends_on:
        - backend
      networks:
        apm_net:
          ipv4_address: ${IP_RAAGE}.21

  backend:
      container_name: ${PROJECT_NAME}_backend
      build:
        context: ${BASE_DIR}/backend
        dockerfile: .DockerfileBackend
      volumes:
        - ${BASE_DIR}/backend:/backend
      ports:
        - ${BACKEND_PORT}:8080
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mysql?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      depends_on:
        - mysql
      networks:
        apm_net:
          ipv4_address: ${IP_RAAGE}.22
  
  nginx:
      container_name: ${PROJECT_NAME}_nginx
      image: nginx:${NGINX_VERSION}
      restart: always
      volumes:
        - ${BASE_DIR}/web/nginx/conf/:/etc/nginx/conf.d
        - ${BASE_DIR}/web/data/conf:/etc/letsencrypt
        - ${BASE_DIR}/web/data/www:/var/www/certbot
      ports:
        - ${NGINX_PORT1}:80
        - ${NGINX_PORT2}:443
      depends_on:
        - frontend
      networks:
        apm_net:
          ipv4_address: ${IP_RAAGE}.23

  mysql:
      container_name: ${PROJECT_NAME}_mysql
      image: mysql:${MYSQL_VERSION}
      ports:
        - ${MYSQL_PORT}:3306
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=mysql
        - TZ=Asia/Seoul
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ${BASE_DIR}/mysql:/var/lib/mysql
      networks:
        apm_net:
          ipv4_address: ${IP_RAAGE}.24

networks:
    apm_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${IP_RAAGE}.0/16
